server:
  port: 8001
## producer配置
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    addresses: 192.168.42.30:5672
    username: admin
    password: Tk2019!
    virtual-host: dev
    publisher-returns: true #返回确认
    publisher-confirms: true # 成功确认
    template:
      mandatory: true
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.javayh.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.javayh.dao: DEBUG